### ISSUE TITLE
weathercan unavailable on CRAN?

### ISSUE THREAD

**Issue by AmeerDotHydro** [ropensci/weathercan#125] opened 2021-08-10 17:10 UTC
seeing the following when installing weathercan
```
install.packages("weathercan")
> install.packages("weathercan")
Installing package into ‘C:/Users/AMUH/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘weathercan’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

ThenI tried to see if the package is available over CRAN

```
ap <- available.packages()
"weathercan" %in% rownames(ap)
[1] FALSE
```

Any thought on how i should go about it? I was able to use R with no issues previously but since last two weeks there seems to be some issues.

**Comment by boshek** [comment] 2021-08-10 17:43
Hi @AmeerDotHydro - just sorting out some issues over here #124. In the mean time you can install weathercan like this:

`install.packages("weathercan", repos = "https://ropensci.r-universe.dev")`

Closing as it this is a duplicate of #123

**Closed by boshek** 2021-08-10 17:43 UTC
