### ISSUE TITLE
Error in if (tz <= 0) tz <- paste0("+", abs(tz)) else tz <- paste0("-", : argument is of length zero

### ISSUE THREAD

**Issue by durraniu** [ropensci/weathercan#59] opened 2018-08-09 16:37 UTC
First of, thank you for creating this package.  

Now, about the error: I am trying to run the following code: 

```
library(weathercan)
> kam <- weather_dl(station_ids = 51423, start = "2016-01-01", end = "2016-02-15")
Error in if (tz <= 0) tz <- paste0("+", abs(tz)) else tz <- paste0("-",  : 
  argument is of length zero
```  

Here's the traceback:  

```
Error in if (tz <= 0) tz <- paste0("+", abs(tz)) else tz <- paste0("-", : argument is of length zero
 3. tz_calc(coords = unique(preamble[, c("lat", "lon")]), etc = TRUE)
 2. weather_format(w = w, interval = interval, tz_disp = tz_disp, string_as = string_as, quiet = quiet, preamble = preamble)
 1. weather_dl(station_ids = 51423, start = "2016-01-01", end = "2016-02-15") 
```            

I have tried different `station_ids` and `start` & `end` but get the same error.

**Comment by steffilazerte** [comment] 2018-08-09 17:15
Ugh, thanks for the bug report! We were calling on a Google API to infer the local timezone, but a) Google has stopped allowing keyless access and b) we didn't have a graceful catch for when the check with google failed. 

I think the most elegant fix will be to use a timezone shapefile to grab the timezones and have a fallback to UTC. I'll see what I can do!

**Comment by steffilazerte** [comment] 2018-08-09 17:54
Hmm, actually this problem just went away, perhaps it was a small blip with Google API? At any rate, I'll put in a fail safe and perhaps look into a self-contained solution for the future. Thanks for alerting us to this!

**Comment by boshek** [comment] 2018-08-09 18:05
One option is to use the `lutz` package: https://cran.r-project.org/web/packages/lutz/index.html

**Comment by steffilazerte** [comment] 2018-08-09 18:07
Hmm, that's not a bad idea either!

**Comment by boshek** [comment] 2018-08-09 18:13
Possibly a less fragile solution.

**Comment by durraniu** [comment] 2018-08-09 19:03
Thank you for your kind responses. I just checked, and yes, I no longer get any error. This is a great package, thank you!

**Comment by ebourlon** [comment] 2018-09-20 13:05
Good morning,
tz_calc is returning timezone this  morning.  I've heard google might have set a quota for its api applications. 
But I am now getting another error: 
kam <- weather_dl(station_ids = 51423, start = "2016-01-01", end = "2016-02-15")
Error in filter_impl(.data, quo) : 
  Evaluation error: invalid argument type.
Any idea?
Thanks

**Comment by steffilazerte** [comment] 2018-09-20 15:03
Glad it's working for you!  the tz_calc error is an intermittent problem with accessing google timezones, if you run into  again, the best you can do right now is just wait an hour or two and see if it clears up. However, we're definitely hoping to get that fixed on our end soon!

**Comment by ebourlon** [comment] 2018-09-20 15:16
Thanks! The weathercan package is such a useful tool. Hopefully ECCC and
google changes will not make it too hard to maintain.
E.

**Comment by ebourlon** [comment] 2018-10-05 13:47
Thanks for reopening ! Behavior of the tz google app is very random. I'm
using the Lutz package in some of my scripts and it's working nice.
E.

**Comment by steffilazerte** [comment] 2018-10-05 13:50
I agree, it's getting worse. I'm working on it right now. I'd love for you to take a look at it once I get it working, let me know how it goes for you! I'll let you know when the fix is posted :)

**Comment by ebourlon** [comment] 2018-10-05 13:52
Sure. I'll test it.
E.

**Comment by steffilazerte** [comment] 2018-10-05 15:19
Alright! The stations data frame now includes a timezone column and I've added `lutz` to suggested dependencies, so that users who update the stations data frame will also get timezones. This way the `weather_dl` function doesn't have to calculate timezones each time, it can just look it up in the stations data frame. Hopefully this will keep things from slowing down.

If you have a moment, could you test a couple things for me?

```
# Update to the dev version:
library(devtools)
install_github("ropensci/weathercan", ref = "dev")

library(weathercan)

# 1. Test general download
w <- weather_dl(station_ids = 51423, start = "2014-01-01", end = "2014-01-31")

# 2. Test stations download
# (I don't expect that this function is often used, but may be relevant to some users)
s <- stations_dl()
```
The second task will take longer, and you might get a message asking you to install a package if you don't already have it.

Thank you!

**Comment by ebourlon** [comment] 2018-10-05 16:08
So far it worked on not-so-recent but up-to-date macbooks pro under R
version 3.4.1 (2017-06-30) -- "Single Candle". I've tested weather_dl,
station_dl and stations_search (we use it a lot) for various coordinate and
repeated commands 10 times in a row: no problem, always got an answer.

I have not been able to run it on our macMinis because devtools cannot be
installed.
I've tried on our ubuntu linux box but I'm getting trouble installing the
lutz package on it (because of V8 install pb). I'm working on it. I know it
can be installed on it because I've done it under our shiny R app server
profile.

Thanks for your time on this package. We almost can't do anything without
it ! We use it to evaluate stability of the atmosphere for plume
modelisation.
E.




Le ven. 5 oct. 2018 à 12:19, Steffi LaZerte <notifications@github.com> a
écrit :

**Comment by boshek** [comment] 2018-10-05 16:10
Works for me @steffilazerte 

What is the thinking behind not using the standard name and rather the offset?
```
> lutz::tz_lookup_coords(52.2, -112., method = "accurate")
[1] "America/Edmonton"
```

**Comment by steffilazerte** [comment] 2018-10-05 16:13
@ebourlon I'm glad to hear it works and that you're finding it so helpful! It seems to be passing most tests, just some problems with systems that can't install the sf and lutz.

Remember that you should be able to run both `windows_dl()` and `stations_search()` without having to install `lutz` and `sf`. You only need to extra packages if you're going to use `stations_dl()`.

@boshek Glad to hear it's working! I use the offset rather than the Olson names because the Olson names include daylight savings (where it exists), whereas the offset does not. This matches the data from ECCC which is in the local timezone without daylight savings.

**Comment by ebourlon** [comment] 2018-10-05 16:15
It worked also on our ubunto box under R version 3.4.2 (2017-09-28) --
"Short Summer".

Thanks!
E.

**Comment by ebourlon** [comment] 2018-10-05 16:21
For people who might have trouble with the install of lutz: I've installed libv8-dev on our server first
(sudo apt-get install libv8-dev). Then the lutz package got installed smoothly.

**Comment by steffilazerte** [comment] 2018-10-05 16:34
No, it's has to be a recognized timezone name under `OlsonNames()`, which means it has to be in the format of `Etc/GMT+-XX`:

```
> grep("Etc", OlsonNames(), value = TRUE)
 [1] "Etc/GMT"       "Etc/GMT0"      "Etc/GMT-0"     "Etc/GMT+0"     "Etc/GMT-1"     "Etc/GMT+1"    
 [7] "Etc/GMT-10"    "Etc/GMT+10"    "Etc/GMT-11"    "Etc/GMT+11"    "Etc/GMT-12"    "Etc/GMT+12"   
[13] "Etc/GMT-13"    "Etc/GMT-14"    "Etc/GMT-2"     "Etc/GMT+2"     "Etc/GMT-3"     "Etc/GMT+3"    
[19] "Etc/GMT-4"     "Etc/GMT+4"     "Etc/GMT-5"     "Etc/GMT+5"     "Etc/GMT-6"     "Etc/GMT+6"    
[25] "Etc/GMT-7"     "Etc/GMT+7"     "Etc/GMT-8"     "Etc/GMT+8"     "Etc/GMT-9"     "Etc/GMT+9"    
[31] "Etc/Greenwich" "Etc/UCT"       "Etc/Universal" "Etc/UTC"       "Etc/Zulu"     
```

Also note that the offset (i.e. -10 or +10) is actually counter-intuitive (the number is the opposite sign than what you'd expect). 

E.g., from <https://en.wikipedia.org/wiki/Tz_database#Area>:
> The special area of "Etc" is used for some administrative zones, particularly for "Etc/UTC" which represents Coordinated Universal Time. In order to conform with the POSIX style, those zone names beginning with "Etc/GMT" have their sign reversed from the standard ISO 8601 convention. In the "Etc" area, zones west of GMT have a positive sign and those east have a negative sign in their name (e.g "Etc/GMT-14" is 14 hours ahead of GMT.)

**Comment by boshek** [comment] 2019-02-11 20:49
@steffilazerte Given the unique status of Newfoundland, do you anticipate any issues with this?
``` r
"Etc/GMT+3.5" %in% OlsonNames()
#> [1] FALSE
```

**Comment by steffilazerte** [comment] 2019-02-11 23:39
Ugh, that is a problem because although there are no errors (with `POSIXct`), it's treated as UTC, which is fine, generally speaking but misleading if you don't know that:

```
library(lubridate)
 
t <- as.POSIXct("2011-01-01 12:00:00", tz = "Etc/GMT+3.5")
t
# [1] "2011-01-01 12:00:00 Etc"

with_tz(t, tz = "Etc/GMT+4")
# [1] "2011-01-01 08:00:00 -04"
with_tz(t, tz = "Etc/GMT+3")
# [1] "2011-01-01 09:00:00 -03"
with_tz(t, tz = "Etc/GMT+2")
# [1] "2011-01-01 10:00:00 -02"

t <- as.POSIXct("2011-01-01 12:00:00", tz = "UTC")
t
# [1] "2011-01-01 12:00:00 UTC"

with_tz(t, tz = "Etc/GMT+4")
# [1] "2011-01-01 08:00:00 -04"
with_tz(t, tz = "Etc/GMT+3")
# [1] "2011-01-01 09:00:00 -03"
with_tz(t, tz = "Etc/GMT+2")
# [1] "2011-01-01 10:00:00 -02"

```

In the end this probably means that we'll have to change everything to just use UTC. I can't think of another way to introduce timezones without daylight savings.

**Closed** 2019-06-07 21:05 UTC

**Comment by ebourlon** [comment] 2019-09-27 12:45
Hi Steffi,
I keep getting this message:* Error in 1:grep("Date/Time", preamble$V1) :
argument of length 0 *when using weather_dl. It was still working ok
yesterday. I've updated the package this morning but it did not fix the
issue.
Any idea?
Thanks!
E.


Le jeu. 20 sept. 2018 à 12:04, Steffi LaZerte <notifications@github.com> a
écrit :

**Comment by steffilazerte** [comment] 2019-09-27 13:36
Hi @ebourlon, this error is actually unrelated to this issue (see #83). I'm hoping to have a fix posted soon.

**Comment by ebourlon** [comment] 2019-09-27 13:44
Thanks. Yes sorry it is a new issue.
Thanks for the package again!
E.

**Comment by steffilazerte** [comment] 2019-09-28 00:23
@ebourlon, if you get the chance, the fix has been posted to the master branch:

```
install.packages("remotes")
remotes::install_github("ropensci/weathercan")
```

Then test as you would normally:

```
library(weathercan)
kam <- weather_dl(station_ids = 51423, start = "2016-01-01", end = "2016-02-15")
kam
```

**Comment by ebourlon** [comment] 2019-09-28 02:05
Thanks! You're fast. I'll try it asap.

I've been using the riem package lately that deliver airport metar
reports.  I have noticed that since at least a year many ECCC airport
stations only report bad weather in the weather description. These stations
are Navcan stations as well and complete weather is provided in metar
reports. Unfortunately the riem package is not as nice as yours. No station
search by distance or data mining tools. I've made my own functions to work
around but I did not have your skills!

Thanks again for the quick response.
E.

**Comment by steffilazerte** [comment] 2019-09-29 17:44
We're on CRAN now, you can update with `install.packages("weathercan")`. 
Good luck!

**Comment by ebourlon** [comment] 2019-09-30 14:36
Thank you. It's working now.

They messed up the metadata....
stations_search("ESTEVAN A") return 3 stations ID which is correct, but
station id 54261 has a wrong start year for the hourly record. This station
only contains hourly data from 2018, not 2015. This lead to no data when
querying that station.
Probably not the only typo in the database.

E.


Le dim. 29 sept. 2019 à 14:44, Steffi LaZerte <notifications@github.com> a
écrit :

**Comment by steffilazerte** [comment] 2019-09-30 14:50
Are you sure? It starts late, but I got data from November 2015:

```
w <- weather_dl(54261)
summary(w$date)

##         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
## "2015-11-27" "2016-11-11" "2017-10-28" "2017-10-28" "2018-10-14" "2019-09-29"
```

**Comment by ebourlon** [comment] 2019-09-30 15:36
I was looking for hourly data in the summer to late October 2015. It is
available from station  53520 and not 54261.
When I do a search of station, I am getting 4 stations with data in 2015. I
use to subset for end and start date, non NA WMO and shortest distance.
Only one is returned.
And when I look for data, there are none.
This works most of the time so far with the updated ECCC database.

> station <- stations_search(coords = c(49.21,-102.97), dist = 10,
interval="hour")
> station
# A tibble: 4 x 15
  prov  station_name station_id climate_id WMO_id TC_id   lat   lon  elev
tz        interval start   end normals distance
  <chr> <chr>             <int> <fct>       <int> <fct> <dbl> <dbl> <dbl>
<chr>     <chr>    <int> <int> <lgl>      <dbl>
1 SK    ESTEVAN A         53520 4012401        NA YEN    49.2 -103.  580.
Etc/GMT+6 hour      2015  2018 FALSE       0
2 SK    ESTEVAN A         54261 4012403     71862 YEN    49.2 -103.  580.
Etc/GMT+6 hour      2015  2019 FALSE       0
3 SK    ESTEVAN           49728 4012410     71559 PJM    49.2 -103.  581.
Etc/GMT+6 hour      2011  2019 FALSE       1.11
4 SK    ESTEVAN A          2896 4012400        NA NA     49.2 -103.  580.
Etc/GMT+6 hour      1953  2015 FALSE       1.11
> station <- subset(station,start <=2015 & end >=2015 & WMO_id !="NA"
&distance ==min(station$distance))
> station
# A tibble: 1 x 15
  prov  station_name station_id climate_id WMO_id TC_id   lat   lon  elev
tz        interval start   end normals distance
  <chr> <chr>             <int> <fct>       <int> <fct> <dbl> <dbl> <dbl>
<chr>     <chr>    <int> <int> <lgl>      <dbl>
1 SK    ESTEVAN A         54261 4012403     71862 YEN    49.2 -103.  580.
Etc/GMT+6 hour      2015  2019 FALSE          0
> weather_dl(station$station_id, start= "2015-08-17", end="2015-09-05")
There are no data for station 54261, in this time range (2015-08-17 to
2015-09-05), for this interval (hour),
Available Station Data:
# A tibble: 2 x 14
  prov  station_name station_id climate_id WMO_id TC_id   lat   lon  elev
tz        interval start   end normals
  <chr> <chr>             <int> <fct>       <int> <fct> <dbl> <dbl> <dbl>
<chr>     <chr>    <int> <int> <lgl>
1 SK    ESTEVAN A         54261 4012403     71862 YEN    49.2 -103.  580.
Etc/GMT+6 day       2018  2019 FALSE
2 SK    ESTEVAN A         54261 4012403     71862 YEN    49.2 -103.  580.
Etc/GMT+6 hour      2015  2019 FALSE
# A tibble: 0 x 0

**Comment by steffilazerte** [comment] 2019-09-30 16:03
Right, the data doesn't start until November 27th 2015. The start year of 2015 is technically correct (i.e. not a typo), the problem is that 2015 isn't a complete year and the data you're looking for is earlier in the year. Unfortunately this level of detail isn't available in the stations data frame. So you won't know the exact start date until you download the data yourself :(

**Comment by ebourlon** [comment] 2019-09-30 16:06
It's the exact same location, ECCC could maybe merge the data carefully.
The weird thing is that it was not causing trouble until they change the
time format.
E.


Le lun. 30 sept. 2019 à 13:03, Steffi LaZerte <notifications@github.com> a
écrit :

**Comment by steffilazerte** [comment] 2019-09-30 16:11
Ahh, I see your problem. Well, I'm glad the package is working for you at least! Any specific questions regarding the data itself are best sent to ECCC, good luck!

**Comment by ebourlon** [comment] 2019-10-01 13:02
another question: we're not able to use both function weather_dl and
station_dl on our linux server. We are getting that message:

> kam <- weather_dl(station_ids = 51423,
+                   start = "2016-01-01", end = "2016-02-15")
Error: Evaluation error: server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none.

s <- stations_dl()
Error: Evaluation error: server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none.


It's working on all the windows and mac computers on the same network.
Other packages that get remote data are still working.
Have you ever seen this? Any idea?

Thanks,
E.



Le lun. 30 sept. 2019 à 13:11, Steffi LaZerte <notifications@github.com> a
écrit :

**Comment by ebourlon** [comment] 2019-10-01 13:49
Maybe some clues: I can download the data using http but there is a
certificate pb when using https. Both are working fine on mac R version.

> t <- fread("
http://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year=2018&Month=10&Day=14&timeframe=1",
fill=TRUE)
trying URL '
http://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year=2018&Month=10&Day=14&timeframe=1
'
downloaded 65 KB

Warning message:
In download.file(input, tmpFile, method = method, mode = "wb", quiet =
!showProgress) :
  downloaded length 66620 != reported length 0

> t <- fread("
https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=1706&Year=2018&Month=10&Day=14&timeframe=1",
fill=TRUE)
Error in curl::curl_download(input, tmpFile, mode = "wb", quiet =
!showProgress) :
  server certificate verification failed. CAfile:
/etc/ssl/certs/ca-certificates.crt CRLfile: none

E.

**Comment by steffilazerte** [comment] 2019-10-02 20:35
I suspect it isn't a `weathercan` issue but rather a problem with the certificates on your server. For example: <https://stackoverflow.com/questions/21181231/server-certificate-verification-failed-cafile-etc-ssl-certs-ca-certificates-c>. If you want to pursue this further as a `weathercan` problem, open a new issue and we can troubleshoot from there.

**Comment by ebourlon** [comment] 2019-10-02 21:09
Thanks Steffi. I'll work on it. I have already done all what is on that
page. I guess our server is messed up..... To many users with admin
priviledges.

Waethercan works perfect. Thanks for keeping it updated.

E.

**Comment by ebourlon** [comment] 2019-10-03 17:37
Package is working again on our ubuntu servers. Adding climate.weather.gc.ca security certificate to our ca-certificates file fixed the "Error: Evaluation error: server certificate verification failed" issue.

**Comment by steffilazerte** [comment] 2019-10-03 19:31
Great, glad to hear it worked out! I'm going to reference this conversation in a new issue to make it easier for people to find if they're searching for a similar problem.

**Comment by ebourlon** [comment] 2019-10-04 09:59
I'll will post the recipe for Ubuntu server.
E.
